version: '3.8'
services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
      - backend_media:/app/media
    environment:
      - DEBUG=False
      - SECRET_KEY=votre_cle_secrete_ici
      - DATABASE_URL=${DATABASE_URL}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS:-localhost,127.0.0.1,54.88.20.85}
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS:-http://localhost:5173,http://127.0.0.1:5173,http://54.88.20.85:8080}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    networks:
      - app-network
    expose:
      - "8000"

  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    volumes:
      - backend_media:/app/media:ro
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  backend_media: